### ISSUE TITLE
"JointBERT-CRF_PhoBERTencoder" could not be found on hugginface

### ISSUE THREAD

**Issue by nguyenvlm** [VinAIResearch/JointIDSF#2]
Hi, I got the following error while running the `run_jointIDSF_PhoBERTencoder.sh`:

```
404 Client Error: Not Found for url: https://huggingface.co/JointBERT-CRF_PhoBERTencoder/3e-5/0.6/100/resolve/main/config.json
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/transformers/configuration_utils.py", line 406, in get_config_dict
    use_auth_token=use_auth_token,
  File "/usr/local/lib/python3.7/dist-packages/transformers/file_utils.py", line 1085, in cached_path
    local_files_only=local_files_only,
  File "/usr/local/lib/python3.7/dist-packages/transformers/file_utils.py", line 1215, in get_from_cache
    r.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/JointBERT-CRF_PhoBERTencoder/3e-5/0.6/100/resolve/main/config.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 139, in <module>
    main(args)
  File "main.py", line 17, in main
    trainer = Trainer(args, train_dataset, dev_dataset, test_dataset)
  File "/content/JointIDSF/trainer.py", line 37, in __init__
    slot_label_lst=self.slot_label_lst,
  File "/usr/local/lib/python3.7/dist-packages/transformers/modeling_utils.py", line 959, in from_pretrained
    **kwargs,
  File "/usr/local/lib/python3.7/dist-packages/transformers/configuration_utils.py", line 360, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/transformers/configuration_utils.py", line 418, in get_config_dict
    raise EnvironmentError(msg)
OSError: Can't load config for 'JointBERT-CRF_PhoBERTencoder/3e-5/0.6/100'. Make sure that:

- 'JointBERT-CRF_PhoBERTencoder/3e-5/0.6/100' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'JointBERT-CRF_PhoBERTencoder/3e-5/0.6/100' is the correct path to a directory containing a config.json file
```

**Comment by joey234** [comment]
Hi, thank you for your interest in our project.

This error means that you did not have a trained JointBERT-CRF model first before training the JointIDSF model.

Can you check if the directory `JointBERT-CRF_PhoBERTencoder/3e-5/0.6/100` is created before the training process of JointIDSF begin?

I just double-check the training script (.sh) files, please try pulling the repo and run again and see if there are still any error.

**Comment by nguyenvlm** [comment]
Thanks for your quick response.

I have re-cloned the repo and still have the same issue. The XLM-R one seems to be fine, but the PhoBERT one always yields the error. The directory `JointBERT-CRF_PhoBERTencoder/3e-5/0.6/100` was not created before the training process.

To give you more details, the code was executed on Google Colab:
```
%%shell
git clone https://github.com/VinAIResearch/JointIDSF.git
cd JointIDSF/
pip3 install -r requirements.txt
```
During the pip installing process I got the following errors, and then those incompatibles were re-installed with the compatible versions:
```
ERROR: torchvision 0.10.0+cu102 has requirement torch==1.9.0, but you'll have torch 1.6.0 which is incompatible.
ERROR: torchtext 0.10.0 has requirement torch==1.9.0, but you'll have torch 1.6.0 which is incompatible.
ERROR: tensorflow 2.2.0 has requirement tensorboard<2.3.0,>=2.2.0, but you'll have tensorboard 2.5.0 which is incompatible.
Installing collected packages: torch, tokenizers, sacremoses, transformers, seqeval, pytorch-crf, gast, tensorflow-estimator, h5py, tensorflow, sentencepiece
  Found existing installation: torch 1.9.0+cu102
    Uninstalling torch-1.9.0+cu102:
      Successfully uninstalled torch-1.9.0+cu102
  Found existing installation: gast 0.4.0
    Uninstalling gast-0.4.0:
      Successfully uninstalled gast-0.4.0
  Found existing installation: tensorflow-estimator 2.5.0
    Uninstalling tensorflow-estimator-2.5.0:
      Successfully uninstalled tensorflow-estimator-2.5.0
  Found existing installation: h5py 3.1.0
    Uninstalling h5py-3.1.0:
      Successfully uninstalled h5py-3.1.0
  Found existing installation: tensorflow 2.5.0
    Uninstalling tensorflow-2.5.0:
      Successfully uninstalled tensorflow-2.5.0
Successfully installed gast-0.3.3 h5py-2.10.0 pytorch-crf-0.7.2 sacremoses-0.0.45 sentencepiece-0.1.96 seqeval-0.0.12 tensorflow-2.2.0 tensorflow-estimator-2.2.0 tokenizers-0.9.4 torch-1.6.0 transformers-4.1.1
```

After the pip installing process, I executed the following colab cell:
```
%%shell
cd /content/JointIDSF/
./run_jointIDSF_PhoBERTencoder.sh
```
and got the [error output](https://github.com/VinAIResearch/JointIDSF/files/6774236/output.txt).

**Comment by joey234** [comment]
I see, try setting `--gpu_id` to `0` in the file `run_jointBERT-CRF_PhoBERTencoder.sh`. It should be ok now.

**Comment by nguyenvlm** [comment]
Thank you. It works now. The issue has gone.
